version: '3.8'

services:
  api:
    build: .
    container_name: orcamento_api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:Nadson1234@postgres:5432/orcamento_db

  postgres:
    image: postgres:15
    container_name: orcamento_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: orcamento_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nadson1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
